version: '3.8'

services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: threads
      POSTGRES_DB: threads
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
